### ISSUE TITLE
CLI Options to load an AVi and use full viewport for processing?

### ISSUE THREAD

**Issue by fallenreaper** [helioalexandre/MouBeAT#1]
I was trying to implement this with a CLI, to be run in a headless mode.  Is this set up to be handled in such a fashion?

I have an AVI, and want the full Viewport to be used for processing and want the Tracking and HeatMap to be allowed.

I didnt see any readme or documentation for setting this up.

**Comment by helioalexandre** [comment]
Sorry for the late reply, but with everything that's going on, haven't payed must attention to this lately.

In short, the answer is no. If I ever get around to make this a plugin, then I'll look into it.

Sorry about that.
